# Generated by Django 5.1.3 on 2024-11-19 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_product_flash_sale_product_new_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_sale_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_flash_sale', models.BooleanField(default=True)),
                ('flash_sale_start_time', models.DateTimeField()),
                ('flash_sale_end_time', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='flash_sale_products/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_product', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='new_products/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_product', to='store.product')),
            ],
        ),
    ]
