# Generated by Django 5.1.3 on 2024-11-19 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_flash_sale_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashsaleproduct',
            name='is_flash_sale',
        ),
        migrations.AlterField(
            model_name='flashsaleproduct',
            name='image',
            field=models.ImageField(upload_to='flash_sales/'),
        ),
        migrations.AlterField(
            model_name='flashsaleproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flashsaleproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
